version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-tracking-bot
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy-network

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-main-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-network
    restart: unless-stopped
    depends_on:
      - discord-bot

networks:
  proxy-network:
    name: proxy-network
    driver: bridge 
